const drugs = [
  ["擬交感神經藥物", "α,β agonist", "Epinephrine"],
  ["擬交感神經藥物", "α,β1 agonist", "Norepinephrine"],
  ["擬交感神經藥物", "D>β>α agonist", "Dopamine"],
  ["擬交感神經藥物", "β agonist", "Isoproterenol"],
  ["擬交感神經藥物", "α1 agonist", "Oxymetazoline"],
  ["擬交感神經藥物", "α1 agonist", "Phenylephrine"],
  ["擬交感神經藥物", "α1 agonist", "Midodrine"],
  ["擬交感神經藥物", "α1 agonist", "Methoxamine"],
  ["擬交感神經藥物", "α2 agonist", "Clonidine"],
  ["擬交感神經藥物", "α2 agonist", "Methyldopa"],
  ["擬交感神經藥物", "α2 agonist", "Tizanidine"],
  ["擬交感神經藥物", "α2 agonist", "Brimonidine"],
  ["擬交感神經藥物", "β1 agonist", "Dobutamine"],
  ["擬交感神經藥物", "β2 agonist", "Metaproterenol"],
  ["擬交感神經藥物", "β2 agonist", "Pirbuterol"],
  ["擬交感神經藥物", "β2 agonist", "Albuterol"],
  ["擬交感神經藥物", "β2 agonist", "Salbutamol"],
  ["擬交感神經藥物", "β2 agonist", "Terbutaline"],
  ["擬交感神經藥物", "β2 agonist", "Procaterol"],
  ["擬交感神經藥物", "β2 agonist", "Salmeterol"],
  ["擬交感神經藥物", "β2 agonist", "Formoterol"],
  ["擬交感神經藥物", "β2 agonist", "Ritodrine"],
  ["擬交感神經藥物", "β3 agonist", "Mirabegron"],
  ["擬交感神經藥物", "D1 agonist", "Fenoldopam"],
  ["擬交感神經藥物", "D2 agonist", "Bromocriptine"],
  ["擬交感神經藥物", "Indirect agonist", "Amphetamine"],
  ["擬交感神經藥物", "Indirect agonist", "Methylphenidate"],
  ["擬交感神經藥物", "Indirect agonist", "Modafinil"],
  ["擬交感神經藥物", "Indirect agonist", "Cocaine"],
  ["擬交感神經藥物", "Indirect agonist", "Amitryptyline"],
  ["擬交感神經藥物", "Indirect agonist", "Tyramine"],
  ["擬交感神經藥物", "Mixed agonist", "Ephedrine"],
  ["擬交感神經藥物", "Mixed agonist", "Pseudoephedrine"],
  ["擬交感神經藥物", "Mixed agonist", "Phenylpropamolamine (PPA)"],
  ["交感神經阻斷劑", "α blocker", "Phenoxybenzamine"],
  ["交感神經阻斷劑", "α blocker", "Phentolamine"],
  ["交感神經阻斷劑", "α1 blocker", "Prazosin"],
  ["交感神經阻斷劑", "α1 blocker", "Doxazosin"],
  ["交感神經阻斷劑", "α1 blocker", "Terazosin"],
  ["交感神經阻斷劑", "α1 blocker", "Tamsulosin"],
  ["交感神經阻斷劑", "α1 blocker", "Indoramin"],
  ["交感神經阻斷劑", "α1 blocker", "Urapidil"],
  ["交感神經阻斷劑", "α2 blocker", "Yohimbine"],
  ["交感神經阻斷劑", "α2 blocker", "Mirtazapine"],
  ["交感神經阻斷劑", "β1 blocker", "Esmolol"],
  ["交感神經阻斷劑", "β1 blocker", "Metoprolol"],
  ["交感神經阻斷劑", "β1 blocker", "Acebutolol"],
  ["交感神經阻斷劑", "β1 blocker", "Nebivolol"],
  ["交感神經阻斷劑", "β1 blocker", "Betaxolol"],
  ["交感神經阻斷劑", "β blocker", "Propranolol"],
  ["交感神經阻斷劑", "β blocker", "Nadolol"],
  ["交感神經阻斷劑", "β blocker", "Pindolol"],
  ["交感神經阻斷劑", "β blocker", "Timolol"],
  ["交感神經阻斷劑", "α,β blocker", "Labetalol"],
  ["交感神經阻斷劑", "α,β blocker", "Carvedilol"],
  ["交感神經阻斷劑", "ISA", "Pindolol"],
  ["交感神經阻斷劑", "ISA", "Carteolol"],
  ["交感神經阻斷劑", "ISA", "Penbutolol"],
  ["交感神經阻斷劑", "ISA", "Acebutolol"],
  ["交感神經阻斷劑", "Neuronal antagonist", "Reserpine"],
  ["交感神經阻斷劑", "Neuronal antagonist", "Guanethidine"],
  ["交感神經阻斷劑", "Neuronal antagonist", "Bretylium"],
  ["交感神經阻斷劑", "Neuronal antagonist", "Metyrosine"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Muscarine"],
  ["膽鹼性致效劑", "Direct nicotinic agonist", "Nicotine"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Lobeline"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Pilocarpine"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Acetylcholine"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Methacholine"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Bethanechol"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Carbachol"],
  ["膽鹼性致效劑", "Direct muscarinic agonist", "Cevimeline"],
  ["膽鹼性致效劑", "Indirect muscarinic agonist", "Physostigmine"],
  ["膽鹼性致效劑", "Indirect muscarinic agonist", "Neostigmine"],
  ["膽鹼性致效劑", "Indirect muscarinic agonist", "Pyridostigmine"],
  ["膽鹼性致效劑", "Indirect muscarinic agonist", "Edrophonium"],
  ["膽鹼性致效劑", "Indirect muscarinic agonist", "Ambenonium"],
  ["膽鹼性致效劑", "Irreversible muscarinic agonist", "Organophosphate"],
  ["膽鹼性致效劑", "Irreversible muscarinic agonist", "Echothiophate"],
  ["膽鹼性致效劑", "AChE reactivator", "Pralidoxime"],
  ["青光眼用藥", "Adrenergic agents", "Epinephrine"],
  ["青光眼用藥", "Adrenergic agents", "Brimonidine"],
  ["青光眼用藥", "Adrenergic agents", "Apraclonidine"],
  ["青光眼用藥", "β blocker", "Timolol"],
  ["青光眼用藥", "β blocker", "Betaxolol"],
  ["青光眼用藥", "Cholinomimetics", "Pilocarpine"],
  ["青光眼用藥", "Cholinomimetics", "Physostigmine"],
  ["青光眼用藥", "Cholinomimetics", "Echothiophate"],
  ["青光眼用藥", "Cholinomimetics", "Carbachol"],
  ["青光眼用藥", "Diuretics", "Acetazolamide"],
  ["青光眼用藥", "PGF2α agonist", "Latanoprost"],
  ["青光眼用藥", "PGF2α agonist", "Bimatoprost"],
  ["青光眼用藥", "PGF2α agonist", "Travoprost"],
  ["青光眼用藥", "PGF2α agonist", "Unoprostone"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Atropine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Homatropine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Cyclopentolate"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Tropicamide"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Scopolamine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Pirenzepine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Propantheline"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Dicyclomine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Clidinium"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Ipratropium"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Tiotropium"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Oxybutynin"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Trihexyphenidyl"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Benztropine"],
  ["膽鹼性拮抗劑", "Muscarinic antagonist", "Biperiden"],
  ["膽鹼性拮抗劑", "Ganglionic (NN) blocker", "Hexamethonium"],
  ["膽鹼性拮抗劑", "Ganglionic (NN) blocker", "Trimethaphan"],
  ["膽鹼性拮抗劑", "Ganglionic (NN) blocker", "Mecamylamine"],
  ["膽鹼性拮抗劑", "NM blocker", "Tubocurarine"],
  ["膽鹼性拮抗劑", "NM blocker", "Mivacurium"],
  ["膽鹼性拮抗劑", "NM blocker", "Atracurium"],
  ["膽鹼性拮抗劑", "NM blocker", "Cisatracurium"],
  ["膽鹼性拮抗劑", "NM blocker", "Pancuronium"],
  ["膽鹼性拮抗劑", "NM blocker", "Vecuronium"],
  ["膽鹼性拮抗劑", "NM blocker", "Rocuronium"],
  ["膽鹼性拮抗劑", "Depolarizing ACh agonist", "Succinylcholine"],
  ["膽鹼性拮抗劑", "Depolarizing ACh agonist", "Decamethonium"],
  ["膽鹼性拮抗劑", "RyR blocker", "Dantrolene"],
  ["中樞性肌肉鬆弛劑", "GABA-A agonist", "Diazepam"],
  ["中樞性肌肉鬆弛劑", "GABA-B agonist", "Baclofen"],
  ["中樞性肌肉鬆弛劑", "α2 agonist", "Tizanidine"],
  ["中樞性肌肉鬆弛劑", "SNAP inhibitor", "Botulinum toxin"],
  ["中樞性肌肉鬆弛劑", "Others", "Hemicholinium"],
  ["中樞性肌肉鬆弛劑", "Others", "Cyclobenzaprine"],
  ["中樞性肌肉鬆弛劑", "Na channel blocker", "Tetrodotoxin (TTX)"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Triazolam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Oxazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Midazolam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Alprazolam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Flunitrazepam (FM2)"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Lorazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Estazolam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Temazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Diazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Clonazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Quazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Prazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Flurazepam"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Clorazepate"],
  ["抗焦慮、鎮靜安眠劑", "Benzodiazepines (BZD)", "Chlordiazepoxide"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Thiopental"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Hexobarbital"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Secobarbital"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Pentobarbital"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Amobarbital"],
  ["抗焦慮、鎮靜安眠劑", "Barbiturates", "Phenobarbital"],
  ["抗焦慮、鎮靜安眠劑", "Z drugs", "Zaleplon"],
  ["抗焦慮、鎮靜安眠劑", "Z drugs", "Zolpidem"],
  ["抗焦慮、鎮靜安眠劑", "Z drugs", "Zopiclone"],
  ["抗焦慮、鎮靜安眠劑", "5-HT1A partial agonist", "Buspirone"],
  ["抗焦慮、鎮靜安眠劑", "H1 blocker", "Hydroxyzine"],
  ["抗焦慮、鎮靜安眠劑", "H1 blocker", "Diphenhydramine"],
  ["抗焦慮、鎮靜安眠劑", "Melatonin receptor agonist", "Ramelteon"],
  ["抗焦慮、鎮靜安眠劑", "Melatonin receptor agonist", "Tasimelteon"],
  ["抗焦慮、鎮靜安眠劑", "Others", "Ethanol"],
  ["抗焦慮、鎮靜安眠劑", "Others", "Chloral hydrate"],
  ["抗憂鬱藥物", "TCA", "Imipramine"],
  ["抗憂鬱藥物", "TCA", "Desipramine"],
  ["抗憂鬱藥物", "TCA", "Clomipramine"],
  ["抗憂鬱藥物", "TCA", "Amitriptyline"],
  ["抗憂鬱藥物", "TCA", "Protriptyline"],
  ["抗憂鬱藥物", "TCA", "Nortriptyline"],
  ["抗憂鬱藥物", "TCA", "Doxepin"],
  ["抗憂鬱藥物", "SSRI", "Fluoxetine"],
  ["抗憂鬱藥物", "SSRI", "Paroxetine"],
  ["抗憂鬱藥物", "SSRI", "Fluvoxamine"],
  ["抗憂鬱藥物", "SSRI", "Sertraline"],
  ["抗憂鬱藥物", "SSRI", "Citalopram"],
  ["抗憂鬱藥物", "SSRI", "Escitalopram"],
  ["抗憂鬱藥物", "SNRI", "Venlafaxine"],
  ["抗憂鬱藥物", "SNRI", "Desvenlafaxine"],
  ["抗憂鬱藥物", "SNRI", "Duloxetine"],
  ["抗憂鬱藥物", "SNRI", "Milnacipran"],
  ["抗憂鬱藥物", "SARI", "Trazodone"],
  ["抗憂鬱藥物", "SARI", "Nefazodone"],
  ["抗憂鬱藥物", "MAOI", "Tranylcypromine"],
  ["抗憂鬱藥物", "MAOI", "Phenelzine"],
  ["抗憂鬱藥物", "MAOI", "Isocarboxazid"],
  ["抗憂鬱藥物", "MAOI", "Moclobemide"],
  ["抗憂鬱藥物", "MAOI", "Selegiline"],
  ["抗憂鬱藥物", "NaSSA", "Mirtazapine"],
  ["抗憂鬱藥物", "NDRI", "Bupropion"],
  ["抗憂鬱藥物", "NRI", "Amoxapine"],
  ["抗憂鬱藥物", "NRI", "Maprotiline"],
  ["情緒安定劑（躁鬱症藥物）", "Lithium", "Lithium"],
  ["抗精神病藥物", "Typical D2 antagonist", "Chlorpromazine"],
  ["抗精神病藥物", "Typical D2 antagonist", "Thioridazine"],
  ["抗精神病藥物", "Typical D2 antagonist", "Fluphenazine"],
  ["抗精神病藥物", "Typical D2 antagonist", "Haloperidol"],
  ["抗精神病藥物", "Typical D2 antagonist", "Thiothixene"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Clozapine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Olanzapine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Quetiapine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Risperidone"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Paliperidone"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Ziprasidone"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Lurasidone"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Asenapine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Aripiprazole"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Brexpiprazole"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Cariprazine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Iloperidone"],
  ["抗精神病藥物", "D2 partial agonist", "Aripiprazole"],
  ["抗精神病藥物", "D2 partial agonist", "Brexpiprazole"],
  ["抗精神病藥物", "D2 partial agonist", "Cariprazine"],
  ["抗精神病藥物", "D2 partial agonist", "Lurasidone"],
  ["抗精神病藥物", "D2 partial agonist", "Risperidone"],
  ["抗精神病藥物", "D2 partial agonist", "Ziprasidone"],
  ["抗精神病藥物", "D2 partial agonist", "Asenapine"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Ziprasidone"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Aripiprazole"],
  ["抗精神病藥物", "Atypical D2, 5-HT2A antagonist", "Amisulpride"],
  ["抗帕金森藥物", "DA prodrug", "Levodopa"],
  ["抗帕金森藥物", "COMT inhibitor", "Tolcapone"],
  ["抗帕金森藥物", "COMT inhibitor", "Entacapone"],
  ["抗帕金森藥物", "MAO-B inhibitor", "Selegiline"],
  ["抗帕金森藥物", "MAO-B inhibitor", "Rasagiline"],
  ["抗帕金森藥物", "DA agonist (ergot)", "Bromocriptine"],
  ["抗帕金森藥物", "DA agonist (ergot)", "Pergolide"],
  ["抗帕金森藥物", "DA agonist (non-ergot)", "Pramipexole"],
  ["抗帕金森藥物", "DA agonist (non-ergot)", "Ropinirole"],
  ["抗帕金森藥物", "DA agonist (non-ergot)", "Rotigotin"],
  ["抗帕金森藥物", "DA agonist (non-ergot)", "Apomorphine"],
  ["抗帕金森藥物", "DA release enhancer", "Amantadine"],
  ["抗帕金森藥物", "Muscarinic antagonist", "Benztropine"],
  ["抗帕金森藥物", "Muscarinic antagonist", "Biperiden"],
  ["抗帕金森藥物", "Muscarinic antagonist", "Trihexyphenidyl"],
  ["抗帕金森藥物", "Muscarinic antagonist", "Procyclidine"],
  ["抗帕金森藥物", "Muscarinic antagonist", "Orphenadrine"],
  ["抗阿茲海默藥物", "AChE inhibitor", "Rivastigmine"],
  ["抗阿茲海默藥物", "AChE inhibitor", "Donepezil"],
  ["抗阿茲海默藥物", "AChE inhibitor", "Galantamine"],
  ["抗阿茲海默藥物", "NMDA blocker", "Memantine"],
  ["抗癲癇藥", "Na channel blocker", "Carbamazepine"],
  ["抗癲癇藥", "Na channel blocker", "Oxcarbazepine"],
  ["抗癲癇藥", "Na channel blocker", "Phenytoin"],
  ["抗癲癇藥", "Na channel blocker", "Fosphenytoin"],
  ["抗癲癇藥", "Na channel blocker", "Lamotrigine"],
  ["抗癲癇藥", "Ca channel blocker", "Ethosuximide"],
  ["抗癲癇藥", "Ca channel blocker", "Trimethadione"],
  ["抗癲癇藥", "Na, Ca channel blocker", "Zonisamide"],
  ["抗癲癇藥", "Na, Ca channel blocker", "Topiramate"],
  ["抗癲癇藥", "Na, Ca, NMDA channel blocker; GABA agonist", "Valproic acid"],
  ["抗癲癇藥", "NMDA blocker", "Felbamate"],
  ["抗癲癇藥", "GABA reuptake inhibitor", "Tiagabine"],
  ["抗癲癇藥", "GABA agonist", "Phenobarbital"],
  ["抗癲癇藥", "GABA agonist", "Primidone"],
  ["抗癲癇藥", "GABA agonist", "Benzodiazepine"],
  ["抗癲癇藥", "GABA agonist", "Gabapentin"],
  ["抗癲癇藥", "GABA agonist", "Pregabalin"],
  ["抗癲癇藥", "GABA agonist", "Vigabatrin"],
  ["抗癲癇藥", "Others", "Levetiracetam"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Morphine"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Meperidine"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Heroin"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Methadone"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Fentanyl"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Sulfentanil"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Alfentanil"],
  ["鴉片類藥物（成癮性止痛劑）", "Strong µ-agonist", "Remifentanil"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Codeine"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Oxycodone"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Hydrocodone"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Dihydrocodeine"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Diphenoxylate"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Difenoxin"],
  ["鴉片類藥物（成癮性止痛劑）", "Mild to moderate µ-agonist", "Loperamide"],
  ["鴉片類藥物（成癮性止痛劑）", "Partial µ-agonist", "Buprenorphine"],
  ["鴉片類藥物（成癮性止痛劑）", "κ-agonist", "Nalbuphine"],
  ["鴉片類藥物（成癮性止痛劑）", "κ-agonist", "Pentazocine"],
  ["鴉片類藥物（成癮性止痛劑）", "Mixed type", "Butorphanol"],
  ["鴉片類藥物（成癮性止痛劑）", "Opioid antagonist", "Naloxone"],
  ["鴉片類藥物（成癮性止痛劑）", "Opioid antagonist", "Naltrexone"],
  ["鴉片類藥物（成癮性止痛劑）", "Opioid antagonist", "Nalmefene"],
  ["頭痛用藥", "NSAIDs", "Acetaminophen"],
  ["頭痛用藥", "air?", "100% O2"],
  ["頭痛用藥", "Ergot alkaloids", "Ergotamine"],
  ["頭痛用藥", "Ergot alkaloids", "Ergonovine"],
  ["頭痛用藥", "Ergot alkaloids", "Dihiydroergotamine"],
  ["頭痛用藥", "Ergot alkaloids", "Methysergide"],
  ["頭痛用藥", "5-HT1B,1D agonist", "Sumatriptan"],
  ["頭痛用藥", "5-HT1F agonist", "Lasmiditan"],
  ["頭痛用藥", "CGRP monoclonal antibody", "Erenumab"],
  ["頭痛用藥", "CGRP monoclonal antibody", "Fremanezumab"],
  ["頭痛用藥", "CGRP monoclonal antibody", "Galcamezumab"],
  ["頭痛用藥", "CGRP antagonist", "Ubrogepant"],
  ["成癮性藥物", "µ-agonist", "Opioids"],
  ["成癮性藥物", "CB1 agonist", "Cannabinoids"],
  ["成癮性藥物", "GABA-B agonist", "γ-hydroxybutyric acid (GHB)"],
  ["成癮性藥物", "5-HT2A agonist", "LSD"],
  ["成癮性藥物", "5-HT2A agonist", "Mescaline"],
  ["成癮性藥物", "5-HT2A agonist", "Psilocybin"],
  ["成癮性藥物", "DA agonist", "Nicotine"],
  ["成癮性藥物", "NMDA antagonist", "Ketamine"],
  ["成癮性藥物", "NMDA antagonist", "PCP"],
  ["成癮性藥物", "GABA agonist", "Benzodiazepines"],
  ["成癮性藥物", "GABA agonist", "Barbiturates"],
  ["成癮性藥物", "DAT, NET inhibitor", "Cocaine"],
  ["成癮性藥物", "VMAT, MAO inhibitor", "Amphetamine"],
  ["成癮性藥物", "VMAT, MAO inhibitor", "MDMA"],
  ["酒精用藥", "µ-antagonist", "Naltrexone"],
  ["酒精用藥", "Mixed", "Acamprosate"],
  ["酒精用藥", "Aldehyde DeH. inhibitor", "Disulfiram"],
  ["酒精用藥", "ADH depleting agent", "Ethanol"],
  ["酒精用藥", "ADH inhibitor", "Fomepizole"],
  ["全身麻醉劑", "Inhaled analgesics", "Nitrous oxide"],
  ["全身麻醉劑", "Inhaled analgesics", "Halothane"],
  ["全身麻醉劑", "Inhaled analgesics", "Sevoflurane"],
  ["全身麻醉劑", "Inhaled analgesics", "Desflurane"],
  ["全身麻醉劑", "Inhaled analgesics", "Isoflurane"],
  ["全身麻醉劑", "Inhaled analgesics", "Enflurane"],
  ["全身麻醉劑", "Inhaled analgesics", "Methoxyflurane"],
  ["全身麻醉劑", "IV injected analgesics", "Thiopental"],
  ["全身麻醉劑", "IV injected analgesics", "Methohexital"],
  ["全身麻醉劑", "IV injected analgesics", "Midazolam"],
  ["全身麻醉劑", "IV injected analgesics", "Diazepam"],
  ["全身麻醉劑", "IV injected analgesics", "Lorazepam"],
  ["全身麻醉劑", "IV injected analgesics", "Propofol"],
  ["全身麻醉劑", "IV injected analgesics", "Ketamine"],
  ["全身麻醉劑", "IV injected analgesics", "Fentanyl"],
  ["全身麻醉劑", "IV injected analgesics", "Etomidate"],
  ["局部麻醉劑", "Ester", "Tetracaine"],
  ["局部麻醉劑", "Ester", "Benzocaine"],
  ["局部麻醉劑", "Ester", "Cocaine"],
  ["局部麻醉劑", "Ester", "Procaine"],
  ["局部麻醉劑", "Amide", "Bupivacaine"],
  ["局部麻醉劑", "Amide", "Lidocaine"],
  ["局部麻醉劑", "Amide", "Prilocaine"],
  ["局部麻醉劑", "Amide", "Ropivacaine"],
  ["局部麻醉劑", "Amide", "Etidocaine"],
  ["利尿劑", "CA inhibitor", "Acetazolamide"],
  ["利尿劑", "Loop diuretics", "Furosemide"],
  ["利尿劑", "Loop diuretics", "Bumetanide"],
  ["利尿劑", "Loop diuretics", "Torsemide"],
  ["利尿劑", "Loop diuretics", "Ethacrynic acid"],
  ["利尿劑", "Thiazide", "Hydrochlorothiazide"],
  ["利尿劑", "Thiazide", "Chlorothiazide"],
  ["利尿劑", "K+ sparing diuretics", "Spironolactone"],
  ["利尿劑", "K+ sparing diuretics", "Eplerenone"],
  ["利尿劑", "K+ sparing diuretics", "Amiloride"],
  ["利尿劑", "K+ sparing diuretics", "Triamterene"],
  ["利尿劑", "Osmotic diuretics", "Mannitol"],
  ["利尿劑", "ADH antagonist", "Conivaptan"],
  ["利尿劑", "ADH antagonist", "Tolvaptan"],
  ["利尿劑", "ADH antagonist", "Demeclocycline"],
  ["降血壓藥物", "ACEI", "Captopril"],
  ["降血壓藥物", "ACEI", "Enalapril"],
  ["降血壓藥物", "ACEI", "Lisinopril"],
  ["降血壓藥物", "ARB", "Valsartan"],
  ["降血壓藥物", "ARB", "Losartan"],
  ["降血壓藥物", "ARB", "Vorsartan"],
  ["降血壓藥物", "ARB", "Saralasin"],
  ["降血壓藥物", "Renin inhibitor", "Aliskiren"],
  ["降血壓藥物", "β-blocker", "[β-blocker]"],
  ["降血壓藥物", "CCB (DHP)", "Amlodipine"],
  ["降血壓藥物", "CCB (DHP)", "Nifedipine"],
  ["降血壓藥物", "CCB (DHP)", "Felodipine"],
  ["降血壓藥物", "CCB (non-DHP)", "Verapamil"],
  ["降血壓藥物", "CCB (non-DHP)", "Diltiazem"],
  ["降血壓藥物", "CCB (non-DHP)", "Bepridil"],
  ["降血壓藥物", "Diuretics", "[Diuretics]"],
  ["降血壓藥物", "K-ATP channel agonist", "Minoxidil"],
  ["降血壓藥物", "K-ATP channel agonist", "Diazoxide"],
  ["降血壓藥物", "D1 agonist", "Fenoldopam"],
  ["降血壓藥物", "α1 blocker", "[α1 blocker]"],
  ["降血壓藥物", "PDE5 inhibitor", "Sildenafil"],
  ["降血壓藥物", "PDE5 inhibitor", "Vardenafil"],
  ["降血壓藥物", "α2 agonist", "Clonidine"],
  ["降血壓藥物", "α2 agonist", "Methyldopa"],
  ["降血壓藥物", "Ganglionic blocker", "Trimethaphan"],
  ["降血壓藥物", "Others", "Hydralazine"],
  ["降血壓藥物", "Others", "Nitroprusside"],
  ["降血壓藥物", "Others", "Guanethidine"],
  ["降血壓藥物", "Others", "Reserpine"],
  ["心絞痛用藥", "Nitrates", "[Nitrates]"],
  ["心絞痛用藥", "Nitrates", "Nitroglycerin"],
  ["心絞痛用藥", "β blocker", "Propranolol"],
  ["心絞痛用藥", "β blocker", "Atenolol"],
  ["心絞痛用藥", "β blocker", "Acebutolol"],
  ["心絞痛用藥", "β blocker", "Metoprolol"],
  ["心絞痛用藥", "CCB", "Dihydropyridine (DHP)"],
  ["心絞痛用藥", "CCB", "Verapamil"],
  ["心絞痛用藥", "CCB", "Diltiazem"],
  ["心絞痛用藥", "Late Na inhibitor", "Ranolazine"],
  ["心絞痛用藥", "If current inhibitor", "Ivabradine"],
  ["心絞痛用藥", "Others (release NO)", "Molsidomine"],
  ["心衰竭用藥", "Diuretics", "[Thiazides]"],
  ["心衰竭用藥", "Diuretics", "Furosemide"],
  ["心衰竭用藥", "Diuretics", "Bumetanide"],
  ["心衰竭用藥", "Diuretics", "Torsemide"],
  ["心衰竭用藥", "Diuretics", "Ethacrynic acid"],
  ["心衰竭用藥", "Diuretics", "Spironolactone"],
  ["心衰竭用藥", "β1 blocker", "Bisoprolol"],
  ["心衰竭用藥", "β1 blocker", "Carvedilol"],
  ["心衰竭用藥", "β1 blocker", "Metoprolol"],
  ["心衰竭用藥", "β1 blocker", "Nebivolol"],
  ["心衰竭用藥", "ACEI", "[ACEI]"],
  ["心衰竭用藥", "ARB", "[ARB]"],
  ["心衰竭用藥", "Direct vessel dilator", "Isosorbide dinitrate"],
  ["心衰竭用藥", "Direct vessel dilator", "Hydralazine"],
  ["心衰竭用藥", "Direct vessel dilator", "Nitroprusside"],
  ["心衰竭用藥", "Direct vessel dilator", "Nitroglycerin"],
  ["心衰竭用藥", "Direct vessel dilator", "Nesiritide"],
  ["心衰竭用藥", "Direct vessel dilator", "Sacubitril"],
  ["心衰竭用藥", "Inotropic agents (digitalis glycosides)", "Digoxin"],
  ["心衰竭用藥", "Inotropic agents (digitalis glycosides)", "Digitoxin"],
  ["心衰竭用藥", "Inotropic agents (β agonist)", "Dobutamine"],
  ["心衰竭用藥", "Inotropic agents (β agonist)", "Dopamine"],
  ["心衰竭用藥", "Inotropic agents (bipyridines / PDE3i)", "Amrinone"],
  ["心衰竭用藥", "Inotropic agents (bipyridines / PDE3i)", "Milrinone"],
  ["心律不整藥物", "Na channel blocker (IA)", "Quinidine"],
  ["心律不整藥物", "Na channel blocker (IA)", "Procainamide"],
  ["心律不整藥物", "Na channel blocker (IA)", "Disopyramide"],
  ["心律不整藥物", "Na channel blocker (IB)", "Lidocaine"],
  ["心律不整藥物", "Na channel blocker (IB)", "Mexiletine"],
  ["心律不整藥物", "Na channel blocker (IB)", "Tocainide"],
  ["心律不整藥物", "Na channel blocker (IB)", "Phenytoin"],
  ["心律不整藥物", "Na channel blocker (IC)", "Flecainide"],
  ["心律不整藥物", "Na channel blocker (IC)", "Propafenone"],
  ["心律不整藥物", "β blocker (II)", "Propranolol"],
  ["心律不整藥物", "β blocker (II)", "Metoprolol"],
  ["心律不整藥物", "β blocker (II)", "Pindolol"],
  ["心律不整藥物", "β blocker (II)", "Esmolol"],
  ["心律不整藥物", "K channel blocker (III)", "Amiodarone"],
  ["心律不整藥物", "K channel blocker (III)", "Dronedarone"],
  ["心律不整藥物", "K channel blocker (III)", "Bretylium"],
  ["心律不整藥物", "K channel blocker (III)", "Sotalol"],
  ["心律不整藥物", "K channel blocker (III)", "Dofetilide"],
  ["心律不整藥物", "K channel blocker (III)", "Ibutilide"],
  ["心律不整藥物", "K channel blocker (III)", "Vernakakant"],
  ["心律不整藥物", "CCB (IV)", "Verapamil"],
  ["心律不整藥物", "CCB (IV)", "Diltiazem"],
  ["心律不整藥物", "CCB (IV)", "Bepridil"],
  ["心律不整藥物", "Others", "Adenosine"],
  ["心律不整藥物", "Others", "Mg^2+"],
  ["心律不整藥物", "Others", "Digoxin"],
  ["降血脂藥", "HMG-CoA reductase inhibitor", "Atorvastatin"],
  ["降血脂藥", "HMG-CoA reductase inhibitor", "Simvastatin"],
  ["降血脂藥", "Niacin", "Niacin"],
  ["降血脂藥", "Fibrates", "Gemfibrozil"],
  ["降血脂藥", "Fibrates", "Bezafibrate"],
  ["降血脂藥", "Fibrates", "Fenofibrate"],
  ["降血脂藥", "Bile acid resins", "Cholestyramine"],
  ["降血脂藥", "Bile acid resins", "Colestipol"],
  ["降血脂藥", "Bile acid resins", "Colesevelam"],
  ["降血脂藥", "Ezetimibe", "Ezetimibe"],
  ["降血脂藥", "PCSK9 inhibitor", "Alirocumab"],
  ["降血脂藥", "PCSK9 inhibitor", "Evolocumab"],
  ["降血脂藥", "Apo B-100 inhibitor", "Mipomersen"],
]